package com.audiobrowser

import com.margelo.nitro.audiobrowser.Variant__query__String_____Promise_Promise_Array_Track____TransformableRequestConfig
import com.margelo.nitro.audiobrowser.Variant_______Promise_Promise_Array_Track____Array_Track__TransformableRequestConfig
import com.margelo.nitro.audiobrowser.Variant__param__BrowserSourceCallbackParam_____Promise_Promise_BrowserList___BrowserList_TransformableRequestConfig
import com.margelo.nitro.audiobrowser.TransformableRequestConfig

// Type aliases to make the generated variant types more readable
typealias SearchSource = Variant__query__String_____Promise_Promise_Array_Track____TransformableRequestConfig
typealias TabsSource = Variant_______Promise_Promise_Array_Track____Array_Track__TransformableRequestConfig
typealias BrowseSource = Variant__param__BrowserSourceCallbackParam_____Promise_Promise_BrowserList___BrowserList_TransformableRequestConfig
typealias MediaSource = TransformableRequestConfig