package com.audiobrowser

import com.margelo.nitro.audiobrowser.Variant_______Promise_Promise_Array_Track____Array_Track__TransformableRequestConfig
import com.margelo.nitro.audiobrowser.Variant__query__String_____Promise_Promise_Array_Track____TransformableRequestConfig

// Type aliases to make the generated variant types more readable
typealias SearchSource =
  Variant__query__String_____Promise_Promise_Array_Track____TransformableRequestConfig

typealias TabsSource =
  Variant_______Promise_Promise_Array_Track____Array_Track__TransformableRequestConfig
